### PR TITLE
Fix: Convert SCSS files to .module.scss (fixes #567)

### LINKED ISSUE #567: SCSS file not getting loaded with webpack
# Bug Report

## Description

SCSS files not getting loaded with webpack dev server because its missing the `.module.` naming convention. I am using CRA for dev.

Related issue on terra-core: https://github.com/cerner/terra-core/issues/1511

Not including others details as related issues explain everything.

## @ Mentions

@bjankord

### PR DESCRIPTION
**Pull request by gyandeeps**
### Summary
Fixes #567. 

Add `.module.` name to all scss files. With this change it will be consistent with all terra packages.

Since `npm install` fails on windows, made changes which i tried in a consumer project (inside node_modules folder). Hopefully travis will tell me if something is wrong. 😸 

Please add your name to the [CONTRIBUTORS.md] file. Adding your name to the [CONTRIBUTORS.md] file signifies agreement to all rights and reservations provided by the [License].

Thanks for contributing to Terra. 
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

**Comment by bjankord** [comment]
It seems this file name change has caused [this mixin file](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-item-view/src/_mixins.scss) to no longer be included in the webpack chunk that includes [this file](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-item-view/src/ItemView.scss). I'm going to look into if moving the mixins into [this file](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-item-view/src/ItemView.scss) resolve this.

**Comment by gyandeeps** [comment]
Hi guys, any ETA on when can this make it to master and then to a release. This is a needed fix as the UI is all over the place without the css. And we have deployments coming up.

**Comment by mjhenkes** [comment]
@gyandeeps We'll release on Thrusday. Normally we could release whenever we want but internal Artifactory has issues and we're going to release closer to the weekend and work with them to bust the cache.

**Comment by gyandeeps** [comment]
sounds good @mjhenkes .

**Pull request merged**
