### PR TITLE
[terra-clinical-detail-view] Set flex value in list-item class

### PR DESCRIPTION
**Pull request by zxeleven**
### Summary

**What was changed:**
Added `flex: auto` to the `list-item` class for the *DetailList* component.

**Why it was changed:**
To resolve an issue reported in the Terra general channel.

Currently, if there are two items in a row in a *DetailList*, each of them will use 50% of the space to fill 100& of the width. However, if there is only one item, it will stay within the min and max width values but will not automatically adjust to take up the remaining space. Setting the flex value to auto will force it to grow and fill the remaining space.

I tested this using the dev site from the thread I mentioned above and it resolves the issue they are seeing. I also tested this using the dev site examples for Detail View and didn't notice any issues with this change.

### Testing

This change was tested using:

- [x] WDIO
- [ ] Jest
- [x] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

#### Visual Testing
**Note:** I removed the last item from the "Indicators" list to highlight the width differences with this change.

Before:
Screenshot 2023-07-19 at 3 06 46 PM

After:
Screenshot 2023-07-19 at 3 51 35 PM

### Reviews

In addition to engineering reviews, this PR needs:

- [x] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-9355 

---

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by kolkheang — APPROVED** [review]

**Review by vinaybhargavar — APPROVED** [review]

**Comment by zxeleven** [comment]
@sdadn @sycombs - This PR is ready for review when you guys get the chance. The description contains more info but it is related to an issue that was posted in Terra general. Thanks!

**Comment by sycombs** [comment]
Can we add a WDIO test for the single item case so we can validate in the future that this behavior doesn't change? We can maybe set the background color to showcase that it fills the whole space.

**Comment by zxeleven** [comment]
> Can we add a WDIO test for the single item case so we can validate in the future that this behavior doesn't change? We can maybe set the background color to showcase that it fills the whole space.

Apologies for the delay, I ran into issues while generating the screenshots for this. Added here: 9ac8aa2d933dd81691e5f94de5c8ddcb36b7672b

**Review by sycombs — APPROVED** [review]

**Review by sdadn — APPROVED** [review]

**Comment by zxeleven** [comment]
Hi @scottwilmarth, when you get a chance can you take a look at this PR? Thanks!

**Review by scottwilmarth — APPROVED** [review]

**Review by kolkheang — APPROVED** [review]

**Comment by sdadn** [comment]
@zxeleven looks good to merge. Thanks for the reminder!

**Pull request merged**
