### PR TITLE
Fix Item View UX Issues

### LINKED ISSUE #115: Item-View, icons do not scale
# Issue Description

At larger font-sizes, icons get cropped off at the bottom. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Icons scaled with font-size.

## Current Behavior

Icons are not scaled with font-size.
screen shot 2017-06-28 at 12 44 08 pm

The person, comment, and information icon are cropped off at the bottom. 

## Steps to Reproduce

1. Open the item-view examples
2. Adjust the browser font-size to very large.

## Environment

* Component Version: 0.2.0
* Browser Name and Version: Chrome 
* Operating System and version (desktop or mobile): v58

### LINKED ISSUE #148: Display Ellipsis with Truncated Text
# Issue Description

At small (phone sized) width text is being cut-off with no indication of truncation. This was noticed in #145. 

From a functional perspective we can't cut-off content without indicating that information is not being displayed. Our two methods have been to wrap extra content to fit, or truncate and show the ellipsis.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
At small width text that is truncated should show an ellipsis.

## Current Behavior

At small (phone sized) width text is being cut-off with no indication of truncation. 

28185350-9b9b6ae0-67dc-11e7-849f-d9b2e4d1c7a6

## Steps to Reproduce

1. Run `npm run start` and navigate to the Item View page. 
2. Shirk the page width. In the `All Elements` example, the text will appear cut off because truncation is being applied (see image above).

### LINKED ISSUE #149: Add Graphic to Item View Accessory Examples
# Issue Description
The Item View nightwatch test example for accessories uses an `` element with `alt` text, but no `src` provided. Adding a graph would add context to these examples, be good for testing consistency among browser comparison, and also make functional verification clearer/easier.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Add graphic to accessory examples.

### PR DESCRIPTION
**Pull request by emilyrohrbough**
### Summary
This PR addresses a few issues with Item View.

1. Fixes Icon Scaling. Closes #115.
2. When adding an example in the nightwatch for scaling, added icons to the accessory examples to provide more context. Closes #149.
3. Fixed Truncation styling. Closes #148.
4. Updated class names to use a '-' instead of a '--'.

@cerner/terra

### CODE REVIEW

**Comment by PaulSolDev** [comment]
Functional review issues in attached doc
[Open source functional review notes.docx](https://github.com/cerner/terra-clinical/files/1163003/Open.source.functional.review.notes.docx)

**Comment by emilyrohrbough** [comment]
> 
image
 The styling applied to two-column item view allows both columns to expand as far as possible, however,  the second column is allowed a maximum width of 60%. It both the first and second items are large in a row, the first item will be given 40% and the second 60%.

> 
image
I updated the accessory content to be an icon to reflect the expected content instead of using fallback text on an img tag.

> 
image
To quickly show truncation on an item view, I applied a width of 900px to the component. I updated the styling to be a max-width of 900px so it will scale down on resize.

> 
image

Could you give me the steps you used to produce this? I am seeing this on the heroku instance on Chrome at a small screen width:

screen shot 2017-07-20 at 11 59 19 am

**Comment by PaulSolDev** [comment]
For Issue 1- I am referring to the vertical alignment of display 1 and 2.  At a large view they are even, but when the content responds to the scaled down browser width display 2 appears to drop down a row (or more depending on browser size).

I will ask Lee to respond to Issue 4.

**Comment by leemurdock** [comment]
@emilyrohrbough I opened ItemView in Safari and then entered responsive design mode and viewed the iPhone6s and iPhone6s+ sizes. Then I opened ItemView in Chrome, selected Developer Tools and viewed the Nexus 6P and Galaxy S5 sizes.

**Comment by dkasper-was-taken** [comment]
@PaulSolDev For issue 1, are the displays wrapping? Each row is vertically align middle, so if column1 is 2 lines, and column2 is 1 line, they will have different tops.

**Comment by PaulSolDev** [comment]
@dkasper-was-taken I'm betting that's the issue.  The align middle is probably throwing off the alignment that I was expecting to see.  I would typically assume these displays would be align top and despite resizing the content would appear consistently aligned.

**Comment by emilyrohrbough** [comment]
@leemurdock I opened the herkou instance and viewed the examples in both the safari and chrome for the mobile sizes you specified. All appear to be applying the truncation as expected. Would you mind checking if this issue is still present? I cannot seem to produce what you are seeing.

itemview truncation screen recording 2017-07-21 at 12 17 pm

**Comment by emilyrohrbough** [comment]
@PaulSolDev Updated to top-align wrapped displays.

**Comment by PaulSolDev** [comment]
@emilyrohrbough  Thank you, I don't see any further issues outside of what you and Lee are currently discussing.

**Comment by neilpfeiffer** [comment]
Tested: PR [#158](https://github.com/cerner/terra-core/pull/158)

**Reviewed:**
- Truncation and Icon Scaling seems to be responding as intended. 


**Pass** |
-----------|
UX Review|

**Comment by leemurdock** [comment]
I see no more issues @emilyrohrbough

**Pull request merged**
