### PR TITLE
[terra-clinical-onset-picker] Added required prop

### PR DESCRIPTION
**Pull request by sugan2416**
### Summary

**What was changed:**

Added required prop to mark fields as required based on granularity level.

**Why it was changed:**

Added required prop as requested to honor required fields.

### Testing

This change was tested using:

- [ ] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [x] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-8663 

---

Thank you for contributing to Terra.
@cerner/terra

image
image

### CODE REVIEW

**Review by supreethmr — COMMENTED** [review]
Why required attribute is not added for granularity select : https://github.com/cerner/terra-clinical/blob/49ab084bc100d407d707201b6ab27323bbeb411c/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L405

and Precision select : https://github.com/cerner/terra-clinical/blob/49ab084bc100d407d707201b6ab27323bbeb411c/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L524

**Comment by sugan2416** [comment]
> Why required attribute is not added for granularity select :
> 
> https://github.com/cerner/terra-clinical/blob/49ab084bc100d407d707201b6ab27323bbeb411c/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L405
> 
> and Precision select :
> 
> https://github.com/cerner/terra-clinical/blob/49ab084bc100d407d707201b6ab27323bbeb411c/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L524

Requirement was to add only to the fields displayed upon granularity selection
image

**Comment by supreethmr** [comment]
> > Why required attribute is not added for granularity select :
> > https://github.com/cerner/terra-clinical/blob/49ab084bc100d407d707201b6ab27323bbeb411c/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L405
> > 
> > and Precision select :
> > https://github.com/cerner/terra-clinical/blob/49ab084bc100d407d707201b6ab27323bbeb411c/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L524
> 
> Requirement was to add only to the fields displayed upon granularity selection image

I don't see it is being added for precision! can you provide me link to precision field with required attribute

**Comment by sugan2416** [comment]
> > > Why required attribute is not added for granularity select :
> > > https://github.com/cerner/terra-clinical/blob/49ab084bc100d407d707201b6ab27323bbeb411c/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L405
> > > 
> > > and Precision select :
> > > https://github.com/cerner/terra-clinical/blob/49ab084bc100d407d707201b6ab27323bbeb411c/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L524
> > 
> > 
> > Requirement was to add only to the fields displayed upon granularity selection image
> 
> I don't see it is being added for precision! can you provide me link to precision field with required attribute

We're not adding for both precision and granularity fields. Its for only the fields rendered on granularity selection.

**Pull request merged**
