### PR TITLE
Scale Item Display Icon with Font Size

### LINKED ISSUE #114: Item-display, icon does not scale
# Issue Description

item-display

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Icon scales with font-size

## Current Behavior

Icon does not scale with font-size. At large font-sizes, icon is no longer visible.

## Steps to Reproduce

1. Navigate to the item display examples 
2. Increase or decrease the font-size of the item-display.

## Environment

* Component Version: 0.2.0
* Browser Name and Version: Chrome 
* Operating System and version (desktop or mobile): Desktop

### PR DESCRIPTION
**Pull request by emilyrohrbough**
### Summary
Resolves #114.

Scaling can be confirmed by:
1 . Navigating to the item display test examples
2.  Click the Icon Scaling Link

@cerner/terra

### CODE REVIEW

**Comment by mjhenkes** [comment]
@emilyrohrbough Is there a way to write a test for this bug? either night watch or jest?

**Comment by emilyrohrbough** [comment]
@mjhenkes I added a nightwatch example and included a test  to capture a screenshot of the scaling. However, there is no good way to verify the svg height within the test. While the font-size is larger than the min-height, nightwatch is able to calculate the svg height as expected. When the font-size is smaller than the min-height set, nightwatch calculation does not account for the min-height value set.

**Comment by mjhenkes** [comment]
@emilyrohrbough good enough for now. When we have screenshot comparison this will be completely covered.

**Comment by PaulSolDev** [comment]
Functional review complete.  No issues identified.

**Comment by emilyrohrbough** [comment]
@neilpfeiffer This is ready for UX review.

**Comment by neilpfeiffer** [comment]
Tested:  PR #156 

**Reviewed:**
- Validated icons scales when changing the element text-size, resolves issue #114 

**Pass** |
-----------|
UX Review|

**Pull request merged**
