### PR TITLE
Add swedish translations

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
Part of the work needed for https://github.com/cerner/terra-core/issues/1700

### CODE REVIEW

**Comment by PaulSolDev** [comment]
Currently unable to see the corresponding language options in the deployment settings drop down: 
image

**Comment by JakeLaCombe** [comment]
@PaulSolDev @bjankord I think that issue maybe a terra toolkit issue that's resolved in that repo. https://github.com/cerner/terra-toolkit/pull/134

Does that sound right?

**Comment by emilyrohrbough** [comment]
@PaulSolDev I updated this PR to pull in the latest terra-dev-site & terra-toolkit changes such that all locales will be visible in this deployment.

**Comment by PaulSolDev** [comment]
@emilyrohrbough  and I walked through the Onset Picker and verified that the translations appear correct for the corresponding languages.  No issues identified.  Verification complete.

**Comment by emilyrohrbough** [comment]
@bjankord I have updated this PR to remove the functional verification changes so it's good to merge once Travis finishes.

**Pull request merged**
