### PR TITLE
Clinical Item Display Color Contrast Accessibility issue #378

### LINKED ISSUE #378: Item Display Accessibility Issues
# Bug Report

## Description
The `terra-clinical-item-display` ItemComment text color does not have enough contrast with the `terra-list` selected background color, the `terra-table` selected background color, or the `terra-table` striped background color.

## Steps to Reproduce
1. [Visit the selectable test page](https://engineering.cerner.com/terra-clinical/#/tests/terra-clinical-item-collection/clinical-item-collection/item-collection-selectable)
2. Test color contrast using Axe in table mode (larger viewport)
3. Test color contrast using Axe in list mode (smaller viewport)
4. [Visit the table styles test page](https://engineering.cerner.com/terra-clinical/#/tests/terra-clinical-item-collection/clinical-item-collection/item-collection-table-styles)
5. Test color contrast using Axe in table mode (larger viewport)

### Selectable
screen shot 2018-07-24 at 2 43 56 pm

```
expected no accessibility violations but got:
	{
  "description": "Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds",
  "help": "Elements must have sufficient color contrast",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.0/color-contrast?application=axeAPI",
  "id": "color-contrast",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": {
            "bgColor": "#e2f2fc",
            "contrastRatio": 3.94,
            "expectedContrastRatio": "4.5:1",
            "fgColor": "#75767d",
            "fontSize": "10.5pt",
            "fontWeight": "normal"
          },
          "id": "color-contrast",
          "impact": "serious",
          "message": "Element has insufficient color contrast of 3.94 (foreground color: #75767d, background color: #e2f2fc, font size: 10.5pt, font weight: normal). Expected contrast ratio of 4.5:1",
          "relatedNodes": [
            {
              "html": "<li tabindex=\"0\" id=\"item3\" class=\"List-module__list-item___1QAkf List-module__selected___rDzz4 List-module__is-selectable___38JEl\">",
              "target": [
                "#item3"
              ]
            }
          ]
        }
      ],
      "failureSummary": "Fix any of the following:\n  Element has insufficient color contrast of 3.94 (foreground color: #75767d, background color: #e2f2fc, font size: 10.5pt, font weight: normal). Expected contrast ratio of 4.5:1",
      "html": "<div class=\"ItemDisplay__text___2ZB9-\">test comment</div>",
      "impact": "serious",
      "none": [],
      "target": [
        "#item3 > .ItemView__item-view___2qBlH.ItemView__one-column___346PH > .ItemView__body___1Uda5 > .ItemComment__item-comment___IfOdl.ItemDisplay__item-display___3gBY_ > .ItemDisplay__text___2ZB9-"
      ]
    }
  ],
  "tags": [
    "cat.color",
    "wcag2aa",
    "wcag143"
  ]
}
```

### Striped
screen shot 2018-07-24 at 3 00 06 pm

```
expected no accessibility violations but got:
	{
  "description": "Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds",
  "help": "Elements must have sufficient color contrast",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.0/color-contrast?application=axeAPI",
  "id": "color-contrast",
  "impact": "serious",
  "nodes": [
    {
      "all": [],
      "any": [
        {
          "data": {
            "bgColor": "#f4f4f4",
            "contrastRatio": 4.11,
            "expectedContrastRatio": "4.5:1",
            "fgColor": "#75767d",
            "fontSize": "10.5pt",
            "fontWeight": "normal"
          },
          "id": "color-contrast",
          "impact": "serious",
          "message": "Element has insufficient color contrast of 4.11 (foreground color: #75767d, background color: #f4f4f4, font size: 10.5pt, font weight: normal). Expected contrast ratio of 4.5:1",
          "relatedNodes": [
            {
              "html": "<tr aria-selected=\"false\" class=\"Table-module__row___3pCTk\">",
              "target": [
                ".Table-module__striped___1iYyS > tbody > tr:nth-child(2)"
              ]
            }
          ]
        }
      ],
      "failureSummary": "Fix any of the following:\n  Element has insufficient color contrast of 4.11 (foreground color: #75767d, background color: #f4f4f4, font size: 10.5pt, font weight: normal). Expected contrast ratio of 4.5:1",
      "html": "<div class=\"ItemDisplay__text___2ZB9-\">test comment</div>",
      "impact": "serious",
      "none": [],
      "target": [
        ".Table-module__striped___1iYyS > tbody > tr:nth-child(2) > .ItemCollection__content-comment___1-Riz > .ItemComment__item-comment___IfOdl.ItemDisplay__item-display___3gBY_ > .ItemDisplay__text___2ZB9-"
      ]
    }
  ],
  "tags": [
    "cat.color",
    "wcag2aa",
    "wcag143"
  ]
}
```
## Expected Behavior
No accessibility errors will be encountered

## Possible Solution
Change one of the colors

### PR DESCRIPTION
**Pull request by ShettyAkarsh**
The terra-clinical-item-display ItemComment text color does not have enough contrast with the  selected background color of terra-list, terra-table or striped background color of terra-table.

Resolves #378

### CODE REVIEW

**Comment by neilpfeiffer** [comment]
Reviewed Code: PR #470
 
**Reviewed:**
- Correctly updates text color to resolve color-contrast issue.
 
 
Verified by @neilpfeiffer.
 
**Pass** |
-----------|
UX Review|

**Comment by neilpfeiffer** [comment]
@ShettyAkarsh looks like you may need to regenerate screenshots.

**Comment by ShettyAkarsh** [comment]
> @ShettyAkarsh looks like you may need to regenerate screenshots using the new colors.

**Comment by ShettyAkarsh** [comment]
> > @ShettyAkarsh looks like you may need to regenerate screenshots using the new colors.

Screenshots has been generated now.

**Comment by emilyrohrbough** [comment]
The item-collection wdio tests for acessibility need to be updated to remove this disabled color-contrast rule:

https://github.com/cerner/terra-clinical/blob/37545fbf50cc4e36fb5dc089fcd5cb644139da2f/packages/terra-clinical-item-collection/tests/wdio/clinical-item-collection-spec.js#L2

**Comment by ShettyAkarsh** [comment]
> The item-collection wdio tests for acessibility need to be updated to remove this disabled color-contrast rule:
> 
> [terra-clinical/packages/terra-clinical-item-collection/tests/wdio/clinical-item-collection-spec.js](https://github.com/cerner/terra-clinical/blob/37545fbf50cc4e36fb5dc089fcd5cb644139da2f/packages/terra-clinical-item-collection/tests/wdio/clinical-item-collection-spec.js#L2-L5)
> 
> Lines 2 to 5 in [37545fb](/cerner/terra-clinical/commit/37545fbf50cc4e36fb5dc089fcd5cb644139da2f)
> 
>  const ignoredA11y = { 
>    // https://github.com/cerner/terra-clinical/issues/378 
>    'color-contrast': { enabled: false }, 
>  };

Removed this color contrast rule.

**Pull request merged**
