### PR TITLE
[terra-clinical-onset-picker] Added screenreader support to announce dynamic content

### PR DESCRIPTION
**Pull request by vinaybhargavar**
### Summary
Based on the selection for granularity, new content is added to the UI. Visually these changes can be seen but the screen reader doesn't announce this content. We need to add screen reader support for dynamic content so that screen reader users are aware that the selections from the combo boxes directly impact the subsequent controls/options/combo boxes that appear further in the process.

**What was changed:**
The region where these changes can be seen on the screen is now changed to be an `aria-live` region with a setting of `polite`.

**Why it was changed:**
To add screen reader support for announcing dynamic content being added on the screen.

### Testing

This change was tested using:

- [ ] WDIO
- [x] Jest
- [x] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

VO + Safari:

https://github.com/cerner/terra-clinical/assets/55503680/10059d35-57c5-4bad-9f1c-e3ef08205d54

VO + Chrome:

https://github.com/cerner/terra-clinical/assets/55503680/6a8450a5-dfd7-43ef-bec0-1b8574beb1f4

JAWS + Edge:

https://github.com/cerner/terra-clinical/assets/55503680/7cf5fdf2-366c-4f2e-b978-fabb97cb0b68

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [x] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-9427 

---

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by zxeleven — APPROVED** [review]

**Comment by vinaybhargavar** [comment]
@sdadn, @sycombs, @eawww - This PR is ready for your review. Thanks.

**Comment by vinaybhargavar** [comment]
@sdadn, @sycombs - Bumping this just in case you missed it. I believe @scottwilmarth wanted to approve this PR but by mistake approved the Terra Doc [PR](https://github.com/cerner/terra-clinical/pull/907) with the following comment. 
Scott - Please correct me if I am wrong here. 

> I think this will generally solve the challenge of no context of changes, though I think we could do better. I'm just not sure how to direct what the better implementation should be. Let's see how the validation work We can certainly re-iterate as needed later.

**Review by sdadn — APPROVED** [review]

**Review by scottwilmarth — APPROVED** [review]

**Review by sycombs — APPROVED** [review]

**Review by sdadn — APPROVED** [review]

**Comment by vinaybhargavar** [comment]
@sdadn, @sycombs  - I see jest snapshot failures unrelated to this PR. I tried running the jest tests locally as well and saw the same tests failing.

**Review by sdadn — APPROVED** [review]

**Comment by sdadn** [comment]
@vinaybhargavar Looks like these changes are from outdated snapshots. I can go ahead and merge this.

**Comment by vinaybhargavar** [comment]
> @vinaybhargavar Looks like these changes are from outdated snapshots. I can go ahead and merge this.

Sounds good, thanks @sdadn.

**Pull request merged**
